export default {
  general: {
    title: 'General',
    labels: {
      search: {
        title: 'Search',
        placeholder: 'Enter text here',
        defaultValue: 'Search',
        isPlaceHolder: true,
        maxLength: 25,
      },
      price: {
        title: 'Price',
        placeholder: 'Enter text here',
        defaultValue: 'Price',
        required: true,
        maxLength: 10,
      },
      currency: {
        title: 'Currency',
        placeholder: 'Enter text here',
        defaultValue: 'Currency',
        required: true,
        maxLength: 10,
      },
      reset: {
        title: 'Reset',
        placeholder: 'Enter text here',
        defaultValue: 'Reset',
        required: true,
        maxLength: 10,
      },
      notAvailable: {
        title: 'N/A',
        placeholder: 'Enter text here',
        defaultValue: 'N/A',
        maxLength: 10,
      },
      open: {
        title: 'Open',
        placeholder: 'Enter text here',
        defaultValue: 'Open',
        required: true,
        maxLength: 8,
      },
      closed: {
        title: 'Closed',
        placeholder: 'Enter text here',
        defaultValue: 'Closed',
        required: true,
        maxLength: 8,
      },
      bookmark: {
        title: 'Bookmark',
        placeholder: 'Enter text here',
        defaultValue: 'Bookmark',
        required: true,
        maxLength: 9,
      },
      bookmarks: {
        title: 'Bookmarks',
        placeholder: 'Enter text here',
        defaultValue: 'Bookmarks',
        required: true,
        maxLength: 12,
      },
      bookmarkResults: {
        title: 'Bookmark Results',
        placeholder: 'Enter text here',
        defaultValue: 'Bookmark Results',
        maxLength: 16,
      },
      enterBookmarkTitleHere: {
        title: 'Enter bookmark title here',
        placeholder: 'Enter text here',
        defaultValue: 'Enter bookmark title here',
        maxLength: 50,
      },
      rateThisLocation: {
        title: 'Rate This Location',
        placeholder: 'Enter text here',
        defaultValue: 'Rate This Location',
        required: true,
        maxLength: 40,
      },
      findWithinThisArea: {
        title: 'Find Within This Area',
        placeholder: 'Enter text here',
        defaultValue: 'Find within this area',
        required: true,
        maxLength: 25,
      },
      findMore: {
        title: 'Find More',
        placeholder: 'Enter text here',
        defaultValue: 'Find More',
        required: true,
        maxLength: 20,
      },
      nearYou: {
        title: 'Near You',
        placeholder: 'Enter text here',
        defaultValue: 'Near You',
        required: true,
        maxLength: 40,
      },
      otherLocations: {
        title: 'Other Locations',
        placeholder: 'Enter text here',
        defaultValue: 'Other Locations',
        required: true,
        maxLength: 40,
      },
      distanceUnitKm: {
        title: 'KM',
        placeholder: 'Enter text here',
        defaultValue: 'KM',
        required: true,
        maxLength: 2,
      },
      distanceUnitMi: {
        title: 'mi',
        placeholder: 'Enter text here',
        defaultValue: 'mi',
        required: true,
        maxLength: 2,
      },
      distanceUnitFt: {
        title: 'ft',
        placeholder: 'Enter text here',
        defaultValue: 'ft',
        required: true,
        maxLength: 2,
      },
      openHours: {
        title: 'Open Hours',
        placeholder: 'Enter text here',
        defaultValue: 'Open Hours',
        maxLength: 25,
      },
      monday: {
        title: 'Monday',
        placeholder: 'Enter text here',
        defaultValue: 'Monday',
        required: true,
        maxLength: 25,
      },
      sunday: {
        title: 'Sunday',
        placeholder: 'Enter text here',
        defaultValue: 'Sunday',
        required: true,
        maxLength: 25,
      },
      tuesday: {
        title: 'Tuesday',
        placeholder: 'Enter text here',
        defaultValue: 'Tuesday',
        required: true,
        maxLength: 25,
      },
      wednesday: {
        title: 'Wednesday',
        placeholder: 'Enter text here',
        defaultValue: 'Wednesday',
        required: true,
        maxLength: 25,
      },
      thursday: {
        title: 'Thursday',
        placeholder: 'Enter text here',
        defaultValue: 'Thursday',
        required: true,
        maxLength: 25,
      },
      friday: {
        title: 'Friday',
        placeholder: 'Enter text here',
        defaultValue: 'Friday',
        required: true,
        maxLength: 25,
      },
      saturday: {
        title: 'Saturday',
        placeholder: 'Enter text here',
        defaultValue: 'Saturday',
        required: true,
        maxLength: 25,
      },
      follow: {
        title: 'Follow',
        placeholder: 'follow',
        defaultValue: 'follow',
        required: true,
        maxLength: 25,
      },
      following: {
        title: 'Following',
        placeholder: 'Following',
        defaultValue: 'Following',
        required: true,
        maxLength: 25,
      },
    }
  },
  sortingOptions: {
    title: 'Sorting Options',
    labels: {
      alphabeticalAsc: {
        title: 'Title (A-Z)',
        placeholder: 'Enter text here',
        defaultValue: 'Title (A-Z)',
        required: true,
        maxLength: 12,
      },
      alphabeticalDsc: {
        title: 'Title (Z-A)',
        placeholder: 'Enter text here',
        defaultValue: 'Title (Z-A)',
        required: true,
        maxLength: 12,
      },
      distance: {
        title: 'Distance',
        placeholder: 'Enter text here',
        defaultValue: 'Distance',
        required: true,
        maxLength: 12,
      },
      recommended: {
        title: 'Recommended',
        placeholder: 'Enter text here',
        defaultValue: 'Recommended',
        required: true,
        maxLength: 12,
      },
      priceDsc: {
        title: '$$$ - $',
        placeholder: 'Enter text here',
        defaultValue: '$$$ - $',
        required: true,
        maxLength: 12,
      },
      priceAsc: {
        title: '$ - $$$',
        placeholder: 'Enter text here',
        defaultValue: '$ - $$$',
        required: true,
        maxLength: 12,
      },
      recent: {
        title: 'Recent',
        placeholder: 'Enter text here',
        defaultValue: 'Recent',
        required: true,
        maxLength: 12,
      },
      mostViewed: {
        title: 'Most Viewed',
        placeholder: 'Enter text here',
        defaultValue: 'Most Viewed',
        required: true,
        maxLength: 12,
      }
    }
  },
  locationEditing: {
    title: 'Location Creating/Editing',
    labels: {
      controlNote: {
        title: 'For full customization options go to the admin Control Panel.',
        placeholder: 'Enter text here',
        defaultValue: 'For full customization options go to the admin Control Panel.',
        required: true,
        maxLength: 100,
      },
      locationDetails: {
        title: 'Location Details',
        placeholder: 'Enter text here',
        defaultValue: 'Location Details',
        maxLength: 25,
      },
      locationName: {
        title: 'Location Title',
        placeholder: 'Enter text here',
        defaultValue: 'Location Title',
        required: true,
        maxLength: 35,
      },
      locationAddress: {
        title: 'Location Address',
        placeholder: 'Enter text here',
        defaultValue: 'Location Address',
        required: true,
        maxLength: 35,
      },
      locationStreetNameAndNumber: {
        title: 'Street Name and Number',
        placeholder: 'Enter text here',
        defaultValue: 'Street Name and Number',
        required: true,
        maxLength: 35,
      },
      locationCustomName: {
        title: 'Location Custom Name',
        placeholder: 'Enter text here',
        defaultValue: 'Location Custom Name',
        required: true,
        maxLength: 35,
      },
      locationSubtitle: {
        title: 'Location Subtitle',
        placeholder: 'Enter text here',
        defaultValue: 'Location Subtitle',
        required: true,
        maxLength: 35,
      },
      locationDescription: {
        title: 'Location Description',
        placeholder: 'Enter text here',
        defaultValue: 'Location Description',
        required: true,
        maxLength: 300,
      },
      descriptionDialogPlaceholder: {
        title: 'Enter your description here',
        placeholder: 'Enter text here',
        defaultValue: 'Enter your description here',
        required: true,
        maxLength: 30,
      },
      descriptionDialogSave: {
        title: 'Save',
        placeholder: 'Enter text here',
        defaultValue: 'Save',
        required: true,
        maxLength: 9,
      },
      descriptionDialogCancel: {
        title: 'Cancel',
        placeholder: 'Enter text here',
        defaultValue: 'Cancel',
        required: true,
        maxLength: 9,
      },
      categories: {
        title: 'Categories',
        placeholder: 'Enter text here',
        defaultValue: 'Categories',
        maxLength: 25,
      },
      chooseCategory: {
        title: 'Choose Category',
        placeholder: 'Enter text here',
        defaultValue: 'Choose Category',
        maxLength: 30,
      },
      starRating: {
        title: 'Star Rating',
        placeholder: 'Enter text here',
        defaultValue: 'Star Rating',
        required: true,
        maxLength: 25,
      },
      showCategory: {
        title: 'Show Category on Location Screen',
        placeholder: 'Enter text here',
        defaultValue: 'Show Category on Location Screen',
        required: true,
        maxLength: 25,
      },
      enableEditing: {
        title: 'Enable Editing',
        placeholder: 'Enter text here',
        defaultValue: 'Enable Editing',
        required: true,
        maxLength: 25,
      },
      priceRange: {
        title: 'Price Range',
        placeholder: 'Enter text here',
        defaultValue: 'Price Range',
        required: true,
        maxLength: 25,
      },
      listImage: {
        title: 'List Image',
        placeholder: 'Enter text here',
        defaultValue: 'List Image',
        required: true,
        maxLength: 25,
      },
      listImageNote: {
        title: 'This is the main location image displayed next to the location info in a list view.',
        placeholder: 'Enter text here',
        defaultValue: 'This is the main location image displayed next to the location info in a list view.',
        required: true,
        maxLength: 110,
      },
      mapNote: {
        title: 'If you need adjustments, drag the map so the pin matches the exact location of your place.',
        placeholder: 'Enter text here',
        defaultValue: 'If you need adjustments, drag the map so the pin matches the exact location of your place.',
        required: true,
        maxLength: 110,
      },
      locationImages: {
        title: 'Location Images',
        placeholder: 'Enter text here',
        defaultValue: 'Location Images',
        required: true,
        maxLength: 25,
      },
      locationImagesNote: {
        title: 'These are the location details images. First image in the list will be displayed as location’s main image.',
        placeholder: 'Enter text here',
        defaultValue: 'These are the location details images. First image in the list will be displayed as location’s main image.',
        required: true,
        maxLength: 110,
      },
      monday: {
        title: 'Mon',
        placeholder: 'Enter text here',
        defaultValue: 'Mon',
        required: true,
        maxLength: 10,
      },
      tuesday: {
        title: 'Tue',
        placeholder: 'Enter text here',
        defaultValue: 'Tue',
        required: true,
        maxLength: 10,
      },
      wednesday: {
        title: 'Wen',
        placeholder: 'Enter text here',
        defaultValue: 'Wen',
        required: true,
        maxLength: 10,
      },
      thursday: {
        title: 'Thu',
        placeholder: 'Enter text here',
        defaultValue: 'Thu',
        required: true,
        maxLength: 10,
      },
      friday: {
        title: 'Fri',
        placeholder: 'Enter text here',
        defaultValue: 'Fri',
        required: true,
        maxLength: 10,
      },
      saturday: {
        title: 'Sat',
        placeholder: 'Enter text here',
        defaultValue: 'Sat',
        required: true,
        maxLength: 10,
      },
      sunday: {
        title: 'Sun',
        placeholder: 'Enter text here',
        defaultValue: 'Sun',
        required: true,
        maxLength: 10,
      },
      fieldRequired: {
        title: 'This Field is Required',
        placeholder: 'Enter text here',
        defaultValue: 'This Field is Required',
        required: true,
        maxLength: 25,
      },
      required: {
        title: 'Required',
        placeholder: 'Enter text here',
        defaultValue: 'Required',
        required: true,
        maxLength: 25,
      },
      invalidTime: {
        title: 'Choose an end time later than the start time.',
        placeholder: 'Enter text here',
        defaultValue: 'Choose an end time later than the start time.',
        required: true,
        maxLength: 45,
      },
      confirmEditingTitle: {
        title: 'Enable Editing',
        placeholder: 'Enter text here',
        defaultValue: 'Enable Editing',
        required: true,
        maxLength: 25,
      },
      confirmEditingMessage: {
        title: 'The location description currently cannot be edited in the app. If you enable editing, the existing description will be deleted and can be replaced with a new description. Are you sure you want to proceed?',
        placeholder: 'Enter text here',
        defaultValue: 'The location description currently cannot be edited in the app. If you enable editing, the existing description will be deleted and can be replaced with a new description. Are you sure you want to proceed?',
        required: true,
        maxLength: 210,
      },
      confirmEditingConfirm: {
        title: 'Confirm',
        placeholder: 'Enter text here',
        defaultValue: 'Confirm',
        required: true,
        maxLength: 15,
      },

      confirmEditingCancel: {
        title: 'Cancel',
        placeholder: 'Enter text here',
        defaultValue: 'Cancel',
        required: true,
        maxLength: 15,
      },
    }
  },
  toast: {
    title: 'Toast Messages',
    labels: {
      bookmarksRemoved: {
        title: 'Bookmark Removed',
        placeholder: 'Enter text here',
        defaultValue: 'Bookmark removed',
        required: true,
        maxLength: 50,
      },
      bookmarksAdded: {
        title: 'Bookmark Added',
        placeholder: 'Enter text here',
        defaultValue: 'Bookmark added',
        required: true,
        maxLength: 50,
      },
      bookmarksError: {
        title: 'Couldn\'t bookmark',
        placeholder: 'Enter text here',
        defaultValue: 'Couldn\'t bookmark',
        required: true,
        maxLength: 50,
      },
      uploadingImages: {
        title: 'Uploading Images',
        placeholder: 'Enter text here',
        defaultValue: 'Uploading images',
        required: true,
        maxLength: 50,
      },
      uploadingComplete: {
        title: 'Uploading Images is Complete',
        placeholder: 'Enter text here',
        defaultValue: 'Uploading Images is Complete',
        required: true,
        maxLength: 50,
      },
      uploadingFailed: {
        title: 'Uploading Images Failed',
        placeholder: 'Enter text here',
        defaultValue: 'Uploading Images Failed',
        required: true,
        maxLength: 50,
      },
      locationSaved: {
        title: 'Location Saved',
        placeholder: 'Enter text here',
        defaultValue: 'Location Saved',
        required: true,
        maxLength: 50,
      },
      alreadyReported: {
        title: 'This item is already reported',
        placeholder: 'Enter text here',
        defaultValue: 'This item is already reported',
        required: true,
        maxLength: 50,
      },
      reportedSuccessfully: {
        title: 'Reported successfully',
        placeholder: 'Enter text here',
        defaultValue: 'Reported successfully',
        required: true,
        maxLength: 50,
      },
      uploadedSuccessfully: {
        title: 'Thanks for sharing your photos',
        placeholder: 'Enter text here',
        defaultValue: 'Thanks for sharing your photos',
        required: true,
        maxLength: 50,
      },
      subscribeToLocationUpdates: {
        title: "You'll now get notifications for location updates.",
        placeholder: "You'll now get notifications for location updates.",
        defaultValue: "You'll now get notifications for location updates.",
        tooltip: "Visible only when the “Allow Sending Notifications” option is enabled on the Settings tab.",
        required: true,
        maxLength: 75,
      },
      unSubscribeFromLocationUpdates: {
        title: "You'll no longer get notifications for location updates.",
        placeholder: "You'll no longer get notifications for location updates.",
        defaultValue: "You'll no longer get notifications for location updates.",
        tooltip: "Visible only when the “Allow Sending Notifications” option is enabled on the Settings tab.",
        required: true,
        maxLength: 75,
      },
      somethingWentWrong: {
        title: 'Something went wrong',
        placeholder: 'Enter text here',
        defaultValue: 'Something went wrong',
        required: true,
        maxLength: 50,
      }
    }
  },
  details: {
    title: 'Details Page',
    labels: {
      bookmark: {
        title: 'Bookmark',
        placeholder: 'Enter text here',
        defaultValue: 'Bookmark',
        required: true,
        maxLength: 25,
      },
      reportAbuse: {
        title: 'Report Abuse',
        placeholder: 'Enter text here',
        defaultValue: 'Report Abuse',
        required: true,
        maxLength: 25,
      },
      share: {
        title: 'Share',
        placeholder: 'Enter text here',
        defaultValue: 'Share',
        required: true,
        maxLength: 25,
      },
      edit: {
        title: 'Edit',
        placeholder: 'Enter text here',
        defaultValue: 'Edit',
        required: true,
        maxLength: 25,
      },
      notifySubscribers: {
        title: 'Notify Subscribers',
        placeholder: 'Enter text here',
        defaultValue: 'Notify Subscribers',
        required: true,
        maxLength: 50,
      },
      addPhotos: {
        title: 'Add Photos',
        placeholder: 'Enter text here',
        defaultValue: 'Add Photos',
        required: true,
        maxLength: 25,
      },
      contributorPrefix: {
        title: 'Contributor Name Prefix',
        placeholder: 'Enter text here',
        defaultValue: 'by',
        required: true,
        maxLength: 15,
      },
      unknownContributor: {
        title: 'Unknown Contributor',
        placeholder: 'Enter text here',
        defaultValue: 'Someone',
        required: true,
        maxLength: 25,
      },
    }
  },
  emptyState: {
    title: 'Empty State',
    labels: {
      emptyCategories: {
        title: 'No Categories Added',
        placeholder: 'Enter text here',
        defaultValue: 'No Categories Added',
        maxLength: 30,
      },
      locationsListBeforeSearch: {
        title: 'Start your search',
        placeholder: 'Enter text here',
        defaultValue: 'Start your search',
        maxLength: 40,
      },
      locationsListAfterSearch: {
        title: 'No locations found within this area',
        placeholder: 'Enter text here',
        defaultValue: 'No locations found within this area',
        maxLength: 40,
      }
    }
  },
};
