export default {
  general: {
    title: 'General',
    labels: {
      search: {
        title: 'Search',
        placeholder: 'Enter text here',
        defaultValue: 'Search',
        isPlaceHolder: true,
        maxLength: 25,
      },
      price: {
        title: 'Price',
        placeholder: 'Enter text here',
        defaultValue: 'Price',
        required: true,
        maxLength: 10,
      },
      currency: {
        title: 'Currency',
        placeholder: 'Enter text here',
        defaultValue: 'Currency',
        required: true,
        maxLength: 10,
      },
      reset: {
        title: 'Reset',
        placeholder: 'Enter text here',
        defaultValue: 'Reset',
        required: true,
        maxLength: 10,
      },
      notAvailable: {
        title: 'N/A',
        placeholder: 'Enter text here',
        defaultValue: 'N/A',
        maxLength: 10,
      },
      open: {
        title: 'Open',
        placeholder: 'Enter text here',
        defaultValue: 'Open',
        required: true,
        maxLength: 8,
      },
      closed: {
        title: 'Closed',
        placeholder: 'Enter text here',
        defaultValue: 'Closed',
        required: true,
        maxLength: 8,
      },
      bookmark: {
        title: 'Bookmark',
        placeholder: 'Enter text here',
        defaultValue: 'Bookmark',
        required: true,
        maxLength: 9,
      },
      bookmarks: {
        title: 'Bookmarks',
        placeholder: 'Enter text here',
        defaultValue: 'Bookmarks',
        required: true,
        maxLength: 12,
      },
      bookmarkResults: {
        title: 'Bookmark Results',
        placeholder: 'Enter text here',
        defaultValue: 'Bookmark Results',
        maxLength: 16,
      },
      enterBookmarkTitleHere: {
        title: 'Enter bookmark title here',
        placeholder: 'Enter text here',
        defaultValue: 'Enter bookmark title here',
        maxLength: 50,
      },
      rateThisLocation: {
        title: 'Rate This Location',
        placeholder: 'Enter text here',
        defaultValue: 'Rate This Location',
        required: true,
        maxLength: 40,
      },
      findWithinThisArea: {
        title: 'Find Within This Area',
        placeholder: 'Enter text here',
        defaultValue: 'Find within this area',
        required: true,
        maxLength: 25,
      },
      findMore: {
        title: 'Find More',
        placeholder: 'Enter text here',
        defaultValue: 'Find More',
        required: true,
        maxLength: 20,
      },
      distanceUnitKm: {
        title: 'KM',
        placeholder: 'Enter text here',
        defaultValue: 'KM',
        required: true,
        maxLength: 2,
      },
      distanceUnitMi: {
        title: 'mi',
        placeholder: 'Enter text here',
        defaultValue: 'mi',
        required: true,
        maxLength: 2,
      },
      distanceUnitFt: {
        title: 'ft',
        placeholder: 'Enter text here',
        defaultValue: 'ft',
        required: true,
        maxLength: 2,
      },
      openHours: {
        title: 'Open Hours',
        placeholder: 'Enter text here',
        defaultValue: 'Open Hours',
        maxLength: 25,
      },
      monday: {
        title: 'Monday',
        placeholder: 'Enter text here',
        defaultValue: 'Monday',
        required: true,
        maxLength: 25,
      },
      sunday: {
        title: 'Sunday',
        placeholder: 'Enter text here',
        defaultValue: 'Sunday',
        required: true,
        maxLength: 25,
      },
      tuesday: {
        title: 'Tuesday',
        placeholder: 'Enter text here',
        defaultValue: 'Tuesday',
        required: true,
        maxLength: 25,
      },
      wednesday: {
        title: 'Wednesday',
        placeholder: 'Enter text here',
        defaultValue: 'Wednesday',
        required: true,
        maxLength: 25,
      },
      thursday: {
        title: 'Thursday',
        placeholder: 'Enter text here',
        defaultValue: 'Thursday',
        required: true,
        maxLength: 25,
      },
      friday: {
        title: 'Friday',
        placeholder: 'Enter text here',
        defaultValue: 'Friday',
        required: true,
        maxLength: 25,
      },
      saturday: {
        title: 'Saturday',
        placeholder: 'Enter text here',
        defaultValue: 'Saturday',
        required: true,
        maxLength: 25,
      },
    }
  },
  sortingOptions: {
    title: 'Sorting Options',
    labels: {
      alphabeticalAsc: {
        title: 'Title (A-Z)',
        placeholder: 'Enter text here',
        defaultValue: 'Title (A-Z)',
        required: true,
        maxLength: 12,
      },
      alphabeticalDsc: {
        title: 'Title (Z-A)',
        placeholder: 'Enter text here',
        defaultValue: 'Title (Z-A)',
        required: true,
        maxLength: 12,
      },
      distance: {
        title: 'Distance',
        placeholder: 'Enter text here',
        defaultValue: 'Distance',
        required: true,
        maxLength: 12,
      },
      recommended: {
        title: 'Recommended',
        placeholder: 'Enter text here',
        defaultValue: 'Recommended',
        required: true,
        maxLength: 12,
      },
      priceDsc: {
        title: '$$$ - $',
        placeholder: 'Enter text here',
        defaultValue: '$$$ - $',
        required: true,
        maxLength: 12,
      },
      priceAsc: {
        title: '$ - $$$',
        placeholder: 'Enter text here',
        defaultValue: '$ - $$$',
        required: true,
        maxLength: 12,
      },
      recent: {
        title: 'Recent',
        placeholder: 'Enter text here',
        defaultValue: 'Recent',
        required: true,
        maxLength: 12,
      },
      mostViewed: {
        title: 'Most Viewed',
        placeholder: 'Enter text here',
        defaultValue: 'Most Viewed',
        required: true,
        maxLength: 12,
      }
    }
  },
  locationEditing: {
    title: 'Location Editing',
    labels: {
      controlNote: {
        title: 'For full customization options go to the admin Control Panel.',
        placeholder: 'Enter text here',
        defaultValue: 'For full customization options go to the admin Control Panel.',
        required: true,
        maxLength: 100,
      },
      locationDetails: {
        title: 'Location Details',
        placeholder: 'Enter text here',
        defaultValue: 'Location Details',
        maxLength: 25,
      },
      locationName: {
        title: 'Location Name',
        placeholder: 'Enter text here',
        defaultValue: 'Location Name',
        required: true,
        maxLength: 35,
      },
      locationAddress: {
        title: 'Location Address',
        placeholder: 'Enter text here',
        defaultValue: 'Location Address',
        required: true,
        maxLength: 35,
      },
      locationSubtitle: {
        title: 'Location Subtitle',
        placeholder: 'Enter text here',
        defaultValue: 'Location Subtitle',
        required: true,
        maxLength: 35,
      },
      categories: {
        title: 'Categories',
        placeholder: 'Enter text here',
        defaultValue: 'Categories',
        maxLength: 25,
      },
      chooseCategory: {
        title: 'Choose Category',
        placeholder: 'Enter text here',
        defaultValue: 'Choose Category',
        maxLength: 30,
      },
      starRating: {
        title: 'Star Rating',
        placeholder: 'Enter text here',
        defaultValue: 'Star Rating',
        required: true,
        maxLength: 25,
      },
      priceRange: {
        title: 'Price Range',
        placeholder: 'Enter text here',
        defaultValue: 'Price Range',
        required: true,
        maxLength: 25,
      },
      listImage: {
        title: 'List Image',
        placeholder: 'Enter text here',
        defaultValue: 'List Image',
        required: true,
        maxLength: 25,
      },
      locationImages: {
        title: 'Location Images',
        placeholder: 'Enter text here',
        defaultValue: 'Location Images',
        required: true,
        maxLength: 25,
      },
      monday: {
        title: 'Mon',
        placeholder: 'Enter text here',
        defaultValue: 'Mon',
        required: true,
        maxLength: 10,
      },
      tuesday: {
        title: 'Tue',
        placeholder: 'Enter text here',
        defaultValue: 'Tue',
        required: true,
        maxLength: 10,
      },
      wednesday: {
        title: 'Wen',
        placeholder: 'Enter text here',
        defaultValue: 'Wen',
        required: true,
        maxLength: 10,
      },
      thursday: {
        title: 'Thu',
        placeholder: 'Enter text here',
        defaultValue: 'Thu',
        required: true,
        maxLength: 10,
      },
      friday: {
        title: 'Fri',
        placeholder: 'Enter text here',
        defaultValue: 'Fri',
        required: true,
        maxLength: 10,
      },
      saturday: {
        title: 'Sat',
        placeholder: 'Enter text here',
        defaultValue: 'Sat',
        required: true,
        maxLength: 10,
      },
      sunday: {
        title: 'Sun',
        placeholder: 'Enter text here',
        defaultValue: 'Sun',
        required: true,
        maxLength: 10,
      },
      required: {
        title: 'Required',
        placeholder: 'Enter text here',
        defaultValue: 'Required',
        required: true,
        maxLength: 25,
      },
      invalidTime: {
        title: 'Choose an end time later than the start time.',
        placeholder: 'Enter text here',
        defaultValue: 'Choose an end time later than the start time.',
        required: true,
        maxLength: 45,
      }
    }
  },
  toast: {
    title: 'Toast Messages',
    labels: {
      bookmarksRemoved: {
        title: 'Bookmark Removed',
        placeholder: 'Enter text here',
        defaultValue: 'Bookmark removed',
        required: true,
        maxLength: 50,
      },
      bookmarksAdded: {
        title: 'Bookmark Added',
        placeholder: 'Enter text here',
        defaultValue: 'Bookmark added',
        required: true,
        maxLength: 50,
      },
      bookmarksError: {
        title: 'Couldn\'t bookmark',
        placeholder: 'Enter text here',
        defaultValue: 'Couldn\'t bookmark',
        required: true,
        maxLength: 50,
      },
      uploadingImages: {
        title: 'Uploading Images',
        placeholder: 'Enter text here',
        defaultValue: 'Uploading images',
        required: true,
        maxLength: 50,
      },
      uploadingComplete: {
        title: 'Uploading Images is Complete',
        placeholder: 'Enter text here',
        defaultValue: 'Uploading Images is Complete',
        required: true,
        maxLength: 50,
      },
      locationSaved: {
        title: 'Location Saved',
        placeholder: 'Enter text here',
        defaultValue: 'Location Saved',
        required: true,
        maxLength: 50,
      }
    }
  },
  emptyState: {
    title: 'Empty State',
    labels: {
      emptyCategories: {
        title: 'No Categories Added',
        placeholder: 'Enter text here',
        defaultValue: 'No Categories Added',
        maxLength: 30,
      },
      locationsListBeforeSearch: {
        title: 'Start your search',
        placeholder: 'Enter text here',
        defaultValue: 'Start your search',
        maxLength: 40,
      },
      locationsListAfterSearch: {
        title: 'No locations found within this area',
        placeholder: 'Enter text here',
        defaultValue: 'No locations found within this area',
        maxLength: 40,
      }
    }
  },
};
